-- MySQL Script generated by MySQL Workbench
-- 06/10/15 19:05:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RealEstateDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RealEstateDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RealEstateDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `RealEstateDB` ;

-- -----------------------------------------------------
-- Table `RealEstateDB`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`user_type` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`user` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `type` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_type`
    FOREIGN KEY (`type`)
    REFERENCES `RealEstateDB`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`gouvernorat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`gouvernorat` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`gouvernorat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`nature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`nature` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`nature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`rubrique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`rubrique` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`rubrique` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`type` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateDB`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateDB`.`post` ;

CREATE TABLE IF NOT EXISTS `RealEstateDB`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `text` VARCHAR(45) NULL,
  `dateCreation` VARCHAR(45) NULL,
  `gouvernorat` INT NOT NULL,
  `rubrique` INT NOT NULL,
  `nature` INT NOT NULL,
  `type` INT NOT NULL,
  `prix` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_id_gouvernorat`
    FOREIGN KEY (`gouvernorat`)
    REFERENCES `RealEstateDB`.`gouvernorat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_nature`
    FOREIGN KEY (`nature`)
    REFERENCES `RealEstateDB`.`nature` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_rubrique`
    FOREIGN KEY (`rubrique`)
    REFERENCES `RealEstateDB`.`rubrique` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_type`
    FOREIGN KEY (`type`)
    REFERENCES `RealEstateDB`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
